language: node_js

node_js:
- "node"
- "9"

# Instalamos grunt en el caso de que no lo esté
before_install:
  - openssl aes-256-cbc -K $encrypted_7b716c4876f6_key -iv $encrypted_7b716c4876f6_iv -in deploy.enc -out deploy -d
  - npm install -g grunt-cli
install:
  - npm install

script:
  - npm test

# Si se ha probado de forma correcta el test, se ejecutará la construcción del archivo 'bundle.js'.
after_success:
  - grunt clean
  - grunt uglify

notifications:
 email:
  recipients:
  - jorgegaguilar@hotmail.es
  - antonio.rdgz.a@gmail.com
  - dinossolatte@gmail.com
  - yuukiizumi@hotmail.es
  - karli-chin@hotmail.com
  on_success: never
  on_failure: always
